# Generated by Django 5.2.8 on 2026-03-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
