# Generated by Django 5.2.8 on 2026-03-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_user_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
